Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  nodes = {"master"=>"192.168.56.10","node1"=>"192.168.56.11","node2"=>"192.168.56.12"}
  nodes.each do |name, ip|
    config.vm.define name do |vm|
      vm.vm.hostname = name
      vm.vm.network "private_network", ip: ip
      vm.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
      end
      vm.vm.provision "shell", inline: <<-SHELL
        sudo apt update -y
        sudo apt install -y docker.io
        sudo usermod -aG docker vagrant
      SHELL
    end
  end
end
